title: Jordan Ellison
email: jellison8640@gmail.com

 main:
  - title: "Home"
    url: /index/
  - title: "lidR Sample"
    url: /workshop1/
  - title: "About Me"
    url: /about/
    
# social links
twitter_username: j_ellison10 # DO NOT include the @ character, or else the build will fail!
github_username:  jellison8640 # DO NOT include the @ character, or else the build will fail!
linkedin: jordan-ellison-a0b628148
show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
      skin: dark
toc: TRUE
highlight: breezedark
