title: Jordan Ellison
site_name: jellison8640
email: jellison8640@gmail.com

navbar:
  title: "Cars"
  left:
  - text: "Home"
   href: index.md
  - text: "Guilds"
   href: guilds.html
    
# social links
twitter_username: j_ellison10 # DO NOT include the @ character, or else the build will fail!
github_username:  jellison8640 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
toc: TRUE
highlight: breezedark
