title: Jordan Ellison
email: jellison8640@gmail.com

nav:
 - Home: 'index.md'
 - Sample: 'worskshop1.md'
 - Post: 'post_sample.md'
 - About Me: 'aboutme.md'
 
# social links
twitter_username: j_ellison10 # DO NOT include the @ character, or else the build will fail!
github_username:  jellison8640 # DO NOT include the @ character, or else the build will fail!
linkedin: jordan-ellison-a0b628148
show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
toc: TRUE
highlight: breezedark
